let predictions = [];
let teamsData = [];
let flags = {};
let goldenBoot = [];
let tournamentSimulation = {};
let knockout = {};

async function loadData() {
  try {
    const [predictionsRes, teamsRes, flagsRes, simRes, goldenBootRes, knockoutRes] = await Promise.all([
      fetch("data/predictions.json"), fetch("data/teams.json"), fetch("data/flags.json"), fetch("data/tournament_simulation.json"), fetch("data/golden_boot.json"), fetch("data/knockout.json")
    ]);
    predictions = await predictionsRes.json(); teamsData = await teamsRes.json(); flags = await flagsRes.json(); tournamentSimulation = await simRes.json(); goldenBoot = await goldenBootRes.json(); knockout = await knockoutRes.json();
    populateFixtures(); renderKpis(); renderTournamentTracker(); renderFixtureList(); renderWinnerChart(); renderGoldenBoot(); renderQualificationOdds(); renderAccuracyPanel(); renderGroupTables(); renderBracket(); renderTeamCards(); showFirstPrediction();
  } catch (error) {
    console.error(error); document.body.insertAdjacentHTML("afterbegin", `<div style="padding:16px;background:#fee2e2;color:#991b1b;">Data loading error. Run all scripts and commit generated JSON files.</div>`);
  }
}
function flag(team){ const code = flags[team]; return code ? `<img class="flag" src="https://flagcdn.com/w40/${code}.png" alt="${team} flag">` : ""; }
function getTeam(name){ return teamsData.find(team => team.name === name); }
function getTeamQualification(teamName){ return tournamentSimulation.qualificationProbabilities?.find(item => item.team === teamName); }
function getTeamTitleChance(teamName){ return tournamentSimulation.winnerProbabilities?.find(item => item.team === teamName)?.winProbability || 0; }
function getTeamFixtures(teamName){ return predictions.filter(match => match.home === teamName || match.away === teamName); }
function getTeamPlayers(teamName){ return goldenBoot.filter(player => player.team === teamName); }
function populateFixtures(){ const select=document.getElementById("fixtureSelect"); if(!select)return; select.innerHTML=predictions.map(match=>`<option value="${match.id}">${match.home} vs ${match.away} - Group ${match.group}</option>`).join(""); }
function showFirstPrediction(){ if(predictions.length && document.getElementById("fixtureSelect")){ document.getElementById("fixtureSelect").value=predictions[0].id; showPrediction(); } }
function renderKpis(){ const c=document.getElementById("kpiGrid"); if(!c)return; const fav=tournamentSimulation.winnerProbabilities?.[0]||{team:"TBD",winProbability:0}; const golden=goldenBoot?.[0]||{player:"TBD",team:"TBD",probability:0}; c.innerHTML=`<div class="kpi-card"><span>Tournament Favourite</span><strong>${flag(fav.team)} ${fav.team}</strong><p class="muted">${fav.winProbability}% title probability</p></div><div class="kpi-card"><span>Golden Boot Favourite</span><strong>${golden.player}</strong><p class="muted">${flag(golden.team)} ${golden.team} · ${golden.probability}%</p></div><div class="kpi-card"><span>Fixtures Modelled</span><strong>${predictions.length}</strong><p class="muted">Group-stage predictions generated</p></div><div class="kpi-card"><span>Simulation Runs</span><strong>10,000</strong><p class="muted">Monte Carlo tournament model</p></div>`; }
function renderTournamentTracker(){ const c=document.getElementById("tournamentTracker"); if(!c)return; const done=predictions.filter(m=>m.status==="completed"||m.actualResult); const goals=done.reduce((t,m)=>t+(m.actualResult?Number(m.actualResult.homeGoals||0)+Number(m.actualResult.awayGoals||0):0),0); const reds=done.reduce((t,m)=>t+(m.redCards?m.redCards.length:0),0); const avg=done.length?(goals/done.length).toFixed(2):"0.00"; const updated=tournamentSimulation.generatedAt?new Date(tournamentSimulation.generatedAt).toLocaleString():"Not available"; c.innerHTML=`<div class="tracker-card"><span>Matches Played</span><strong>${done.length}</strong></div><div class="tracker-card"><span>Matches Remaining</span><strong>${predictions.length-done.length}</strong></div><div class="tracker-card"><span>Goals Scored</span><strong>${goals}</strong></div><div class="tracker-card"><span>Avg Goals/Game</span><strong>${avg}</strong></div><div class="tracker-card"><span>Red Cards</span><strong>${reds}</strong></div><div class="tracker-card wide"><span>Last Model Update</span><strong>${updated}</strong></div>`; }
function renderFixtureList(){ const c=document.getElementById("fixtureList"); if(!c)return; const s=document.getElementById("teamSearch")?.value.toLowerCase()||""; const g=document.getElementById("groupFilter")?.value||"all"; const filtered=predictions.filter(m=>(m.home.toLowerCase().includes(s)||m.away.toLowerCase().includes(s))&&(g==="all"||m.group===g)); const grouped={}; filtered.forEach(m=>{ if(!grouped[m.group])grouped[m.group]=[]; grouped[m.group].push(m); }); c.innerHTML=Object.keys(grouped).sort().map(group=>`<div class="fixture-group"><h3>Group ${group}</h3>${grouped[group].map(m=>fixtureRow(m)).join("")}</div>`).join("")||"<p class='muted'>No matches found.</p>"; }
function fixtureRow(m){ const score=m.actualResult?`${m.actualResult.homeGoals}-${m.actualResult.awayGoals}`:m.predictedScore; return `<div class="fixture-row" onclick="selectMatch('${m.id}')"><div class="fixture-teams"><strong>${flag(m.home)} ${m.home}</strong><span>${score}</span><strong>${flag(m.away)} ${m.away}</strong></div><div class="fixture-meta"><span>${formatDate(m.date)}</span><span>${m.stadium||"Venue TBD"}</span><span>${m.probabilities.home}% · ${m.probabilities.draw}% · ${m.probabilities.away}%</span><span>Winner: ${flag(m.predictedWinner)} ${m.predictedWinner}</span><span class="confidence-pill ${confidenceClass(m.confidence)}">${m.confidence}</span><span>Likely scorer: ${m.likelyScorer.name}</span>${m.actualResult?`<span class="completed-pill">Completed</span>`:""}</div></div>`; }
function showPrediction(){ const id=document.getElementById("fixtureSelect").value; const m=predictions.find(x=>String(x.id)===String(id)); if(!m)return; const score=m.actualResult?`${m.actualResult.homeGoals}-${m.actualResult.awayGoals}`:m.predictedScore; document.getElementById("prediction").innerHTML=`<h3>${flag(m.home)} ${m.home} vs ${flag(m.away)} ${m.away}</h3><div class="prediction-grid"><div><strong>${m.actualResult?"Final score":"Predicted score"}</strong><p class="big-number">${score}</p></div><div><strong>Predicted winner</strong><p>${flag(m.predictedWinner)} ${m.predictedWinner}</p></div><div><strong>Confidence</strong><p><span class="confidence-pill ${confidenceClass(m.confidence)}">${m.confidence}</span></p></div></div><div class="info-grid"><div class="info-card"><strong>Win probabilities</strong>${probabilityLine(m.home,m.probabilities.home)}${probabilityLine("Draw",m.probabilities.draw)}${probabilityLine(m.away,m.probabilities.away)}</div><div class="info-card"><strong>Player intelligence</strong>Likely scorer: ${m.likelyScorer.name}<br>Team: ${flag(m.likelyScorer.team)} ${m.likelyScorer.team}<br>Scorer probability: ${m.likelyScorer.probability}%</div><div class="info-card"><strong>Cards model</strong>${flag(m.home)} ${m.home}: ${m.redCardRisk[m.home]}% red-card risk<br>${flag(m.away)} ${m.away}: ${m.redCardRisk[m.away]}% red-card risk</div><div class="info-card"><strong>Venue conditions</strong>${m.stadium}, ${m.city}<br>Kickoff: ${formatDate(m.date)}<br>Heat: ${m.factors.heatImpact} (${m.factors.venueHeatRisk}/10)<br>Altitude: ${m.factors.altitudeImpact} (${m.factors.altitude}m)</div><div class="info-card"><strong>${flag(m.home)} ${m.home} travel</strong>${m.travel[m.home].distanceKm.toLocaleString()} km<br>Impact: ${m.travel[m.home].impact}<br>Penalty: -${m.travel[m.home].penalty} pts</div><div class="info-card"><strong>${flag(m.away)} ${m.away} travel</strong>${m.travel[m.away].distanceKm.toLocaleString()} km<br>Impact: ${m.travel[m.away].impact}<br>Penalty: -${m.travel[m.away].penalty} pts</div></div><hr><h3>Why this prediction?</h3><p>${m.explanation?.summary||"No explanation available."}</p><ul>${(m.explanation?.strongestFactors||[]).map(f=>`<li><strong>${f.advantage}</strong> advantage: ${f.factor} +${f.difference}</li>`).join("")}</ul><h3>Model notes</h3><ul>${(m.notes||[]).map(n=>`<li>${n}</li>`).join("")}</ul>`; }
function probabilityLine(label,value){ const l=label==="Draw"?"Draw":`${flag(label)} ${label}`; return `<div class="chart-row"><div class="chart-label"><span>${l}</span><span>${value}%</span></div><div class="chart-bar"><span style="width:${value}%"></span></div></div>`; }
function selectMatch(id){ const s=document.getElementById("fixtureSelect"); if(!s)return; s.value=id; showPrediction(); document.getElementById("prediction").scrollIntoView({behavior:"smooth",block:"start"}); }
function renderWinnerChart(){ const c=document.getElementById("winnerChart"); if(!c||!tournamentSimulation.winnerProbabilities)return; c.innerHTML=tournamentSimulation.winnerProbabilities.slice(0,12).map(t=>`<div class="chart-row"><div class="chart-label"><span>${flag(t.team)} ${t.team}</span><span>${t.winProbability}%</span></div><div class="chart-bar"><span style="width:${t.winProbability*4}%"></span></div></div>`).join(""); }
function renderGoldenBoot(){ const c=document.getElementById("goldenBoot"); if(!c||!goldenBoot.length)return; c.innerHTML=goldenBoot.slice(0,12).map(p=>`<div class="chart-row"><div class="chart-label"><span>${flag(p.team)} ${p.player}</span><span>${p.probability}%</span></div><div class="chart-bar"><span style="width:${p.probability*5}%"></span></div></div>`).join(""); }
function renderQualificationOdds(){ const c=document.getElementById("qualificationOdds"); if(!c||!tournamentSimulation.qualificationProbabilities)return; const grouped={}; tournamentSimulation.qualificationProbabilities.forEach(t=>{if(!grouped[t.group])grouped[t.group]=[];grouped[t.group].push(t);}); c.innerHTML=Object.keys(grouped).sort().map(g=>`<div class="qualification-card"><h3>Group ${g}</h3>${grouped[g].map(t=>`<div class="qualification-row"><div><strong>${flag(t.team)} ${t.team}</strong><p class="muted">Win group: ${t.groupWinProbability}% | Runner-up: ${t.runnerUpProbability}% | Best third: ${t.thirdPlaceQualifyProbability}%</p></div><div class="qualify-score"><strong>${t.qualifyProbability}%</strong><span>Qualify</span></div></div><div class="chart-bar"><span style="width:${t.qualifyProbability}%"></span></div>`).join("")}</div>`).join(""); }
function renderAccuracyPanel(){ const c=document.getElementById("accuracyPanel"); if(!c)return; const a=tournamentSimulation.predictionAccuracy||{matchesPredicted:0,correctWinnerPercentage:0,correctScorePercentage:0,averageGoalError:0}; c.innerHTML=`<div class="tracker-card"><span>Matches Checked</span><strong>${a.matchesPredicted}</strong></div><div class="tracker-card"><span>Correct Winner</span><strong>${a.correctWinnerPercentage}%</strong></div><div class="tracker-card"><span>Correct Score</span><strong>${a.correctScorePercentage}%</strong></div><div class="tracker-card"><span>Avg Goal Error</span><strong>${a.averageGoalError}</strong></div>`; }
function renderTeamCards(){ const c=document.getElementById("teamCards"); if(!c)return; c.innerHTML=[...teamsData].sort((a,b)=>b.elo-a.elo).map(t=>`<div class="team-card" onclick="showTeamDashboard('${t.name}')"><strong>${flag(t.name)} ${t.name}</strong><p class="muted">${t.confederation} | Group ${t.group}</p>${statBar("Attack",t.attack)}${statBar("Defence",t.defence)}${statBar("Form",t.recentForm)}<span class="score-pill">Elo ${t.elo}</span></div>`).join(""); }
function statBar(label,value){ return `<div class="stat-bar"><label><span>${label}</span><span>${value}</span></label><div class="bar"><span style="width:${value}%"></span></div></div>`; }
function renderGroupTables(){ const c=document.getElementById("groups"); if(!c||!tournamentSimulation.groupTables)return; c.innerHTML=Object.keys(tournamentSimulation.groupTables).sort().map(g=>`<div class="group-table"><h3>Group ${g}</h3><table><thead><tr><th>Team</th><th>P</th><th>W</th><th>D</th><th>L</th><th>GD</th><th>Pts</th></tr></thead><tbody>${tournamentSimulation.groupTables[g].map(r=>`<tr><td>${flag(r.team)} ${r.team}</td><td>${r.played}</td><td>${r.won}</td><td>${r.drawn}</td><td>${r.lost}</td><td>${r.goalDifference}</td><td><strong>${r.points}</strong></td></tr>`).join("")}</tbody></table></div>`).join(""); }
function renderBracket(){ const c=document.getElementById("bracket"); if(!c)return; if(!knockout.rounds){c.innerHTML="<p class='muted'>Knockout bracket has not been generated yet.</p>";return;} c.innerHTML=knockout.rounds.map(r=>`<div class="bracket-round"><h3>${r.name}</h3>${r.matches.map((m,i)=>`<div class="match"><strong>${i+1}</strong>. ${flag(m.home)} ${m.home}<br>vs ${flag(m.away)} ${m.away}${m.homeQualification?`<br><small>${m.homeQualification} vs ${m.awayQualification}</small>`:""}</div>`).join("")}</div>`).join(""); }
function showTeamDashboard(name){ const t=getTeam(name); if(!t)return; const q=getTeamQualification(name)||{}; const title=getTeamTitleChance(name); const fixtures=getTeamFixtures(name); const players=getTeamPlayers(name); document.getElementById("teamModalContent").innerHTML=`<h2>${flag(t.name)} ${t.name}</h2><p class="muted">${t.confederation} · Group ${t.group}</p><div class="prediction-grid"><div><strong>FIFA Rank Seed</strong><p class="big-number">${t.fifaRank}</p></div><div><strong>Elo</strong><p class="big-number">${t.elo}</p></div><div><strong>Title Chance</strong><p class="big-number">${title}%</p></div></div><div class="info-grid"><div class="info-card"><strong>Team Ratings</strong>${statBar("Attack",t.attack)}${statBar("Defence",t.defence)}${statBar("Recent form",t.recentForm)}${statBar("World Cup history",t.worldCupHistory)}</div><div class="info-card"><strong>Qualification Model</strong>Qualify: ${q.qualifyProbability||0}%<br>Win group: ${q.groupWinProbability||0}%<br>Runner-up: ${q.runnerUpProbability||0}%<br>Best third-place route: ${q.thirdPlaceQualifyProbability||0}%</div><div class="info-card"><strong>Key Players</strong>${players.length?players.map(p=>`${p.player||p.name} ${p.probability?`(${p.probability}%)`:""}`).join("<br>"):"No key player data available."}</div><div class="info-card"><strong>Updates</strong>Injuries: ${(t.injuries||[]).length}<br>Suspensions: ${(t.suspensions||[]).length}<br>${t.notes||""}</div></div><h3>Fixtures</h3>${fixtures.map(m=>fixtureRow(m)).join("")}`; document.getElementById("teamModal").classList.remove("hidden"); }
function hideTeamModal(){ document.getElementById("teamModal").classList.add("hidden"); }
function closeTeamModal(e){ if(e.target.id==="teamModal")hideTeamModal(); }
function askChat(){ const input=document.getElementById("chatInput").value.toLowerCase(); const out=document.getElementById("chatOutput"); if(!input.trim()){out.innerHTML="Ask about a team, group, title odds, qualification, Golden Boot or model logic.";return;} const team=teamsData.find(t=>input.includes(t.name.toLowerCase())); if(team){const q=getTeamQualification(team.name)||{}; const title=getTeamTitleChance(team.name); out.innerHTML=`<h3>${flag(team.name)} ${team.name}</h3><p>${team.name} has a ${q.qualifyProbability||0}% qualification probability and a ${title}% title probability.</p>${statBar("Attack",team.attack)}${statBar("Defence",team.defence)}${statBar("Recent form",team.recentForm)}${statBar("World Cup history",team.worldCupHistory)}`;return;} if(input.includes("dark horse")){const dark=tournamentSimulation.winnerProbabilities.filter(t=>t.winProbability>=2&&t.winProbability<=8).slice(0,5);out.innerHTML=`<h3>Dark Horse Candidates</h3>${dark.map(t=>`<p>${flag(t.team)} ${t.team}: ${t.winProbability}% title probability</p>`).join("")}`;return;} if(input.includes("golden boot")||input.includes("top scorer")){out.innerHTML=`<h3>Golden Boot Model</h3>${goldenBoot.slice(0,8).map(p=>`<p>${flag(p.team)} ${p.player}: ${p.probability}%</p>`).join("")}`;return;} out.innerHTML=`<h3>Model Logic</h3><p>The model combines seeded team strength, form, attack, defence, World Cup history, travel, heat, altitude, injuries, suspensions and Monte Carlo simulations.</p>`; }
function confidenceClass(confidence){ if(!confidence)return"confidence-low"; const v=confidence.toLowerCase(); if(v.includes("high"))return"confidence-high"; if(v.includes("medium"))return"confidence-medium"; return"confidence-low"; }
function formatDate(d){ if(!d)return"Date TBD"; return new Date(d).toLocaleString(undefined,{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}); }
function toggleTheme(){ document.body.classList.toggle("dark"); localStorage.setItem("theme",document.body.classList.contains("dark")?"dark":"light"); }
function loadTheme(){ if(localStorage.getItem("theme")==="dark")document.body.classList.add("dark"); }
loadTheme(); loadData();
