const fs = require("fs");
const teams = JSON.parse(fs.readFileSync("data/teams.json", "utf8"));
const predictions = JSON.parse(fs.readFileSync("data/predictions.json", "utf8"));
const getTeam = name => teams.find(t => t.name === name);
function teamStrength(team) { return team.elo * 0.035 + team.recentForm * 0.18 + team.squadRating * 0.18 + team.attack * 0.14 + team.defence * 0.14 + team.worldCupHistory * 0.12 - team.disciplineRisk * 0.05 - (team.injuries || []).length * 1.1 - (team.suspensions || []).length * 1.5; }
function simulateScore(home, away, match) { if (match.actualResult) return { homeGoals: Number(match.actualResult.homeGoals), awayGoals: Number(match.actualResult.awayGoals) }; const diff = teamStrength(home) - teamStrength(away); return { homeGoals: Math.max(0, Math.round(1.25 + diff / 20 + Math.random() * 1.6)), awayGoals: Math.max(0, Math.round(1.15 - diff / 20 + Math.random() * 1.6)) }; }
function predictedScore(match) { if (match.actualResult) return { homeGoals: Number(match.actualResult.homeGoals), awayGoals: Number(match.actualResult.awayGoals) }; return { homeGoals: Number(match.predictedScore.split("-")[0]), awayGoals: Number(match.predictedScore.split("-")[1]) }; }
function simulateWinner(teamA, teamB) { const scoreA = teamStrength(getTeam(teamA)) + Math.random() * 18; const scoreB = teamStrength(getTeam(teamB)) + Math.random() * 18; return scoreA >= scoreB ? teamA : teamB; }
function emptyTables() { const tables = {}; teams.forEach(team => { if (!tables[team.group]) tables[team.group] = {}; tables[team.group][team.name] = { team: team.name, played:0, won:0, drawn:0, lost:0, goalsFor:0, goalsAgainst:0, goalDifference:0, points:0 }; }); return tables; }
function applyResultToTable(tables, match, r) { const h=tables[match.group][match.home], a=tables[match.group][match.away]; h.played++; a.played++; h.goalsFor+=r.homeGoals; h.goalsAgainst+=r.awayGoals; a.goalsFor+=r.awayGoals; a.goalsAgainst+=r.homeGoals; if(r.homeGoals>r.awayGoals){h.won++;a.lost++;h.points+=3}else if(r.homeGoals<r.awayGoals){a.won++;h.lost++;a.points+=3}else{h.drawn++;a.drawn++;h.points++;a.points++} }
function sortTables(tables) { const finalTables = {}; Object.keys(tables).forEach(group => { finalTables[group] = Object.values(tables[group]).map(t => ({...t, goalDifference:t.goalsFor-t.goalsAgainst})).sort((a,b)=>b.points-a.points||b.goalDifference-a.goalDifference||b.goalsFor-a.goalsFor||teamStrength(getTeam(b.team))-teamStrength(getTeam(a.team))); }); return finalTables; }
function buildGroupTables(randomized=false) { const tables=emptyTables(); predictions.filter(m=>m.stage==="Group Stage").forEach(m=>{ const h=getTeam(m.home), a=getTeam(m.away); applyResultToTable(tables,m,randomized?simulateScore(h,a,m):predictedScore(m)); }); return sortTables(tables); }
function getQualifiedTeams(groupTables){ const q=[]; Object.keys(groupTables).sort().forEach(g=>{q.push({...groupTables[g][0],qualification:`Winner Group ${g}`});q.push({...groupTables[g][1],qualification:`Runner-up Group ${g}`})}); const third=Object.keys(groupTables).map(g=>({...groupTables[g][2],qualification:`Third Group ${g}`})).sort((a,b)=>b.points-a.points||b.goalDifference-a.goalDifference||b.goalsFor-a.goalsFor||teamStrength(getTeam(b.team))-teamStrength(getTeam(a.team))).slice(0,8); return [...q,...third]; }
function simulateKnockout(qualified){ let round=qualified.map(t=>t.team); while(round.length>1){const next=[]; for(let i=0;i<round.length;i+=2) next.push(simulateWinner(round[i],round[i+1])); round=next;} return round[0]; }
function monteCarlo(runs=10000){ const winnerCounts={}, qualifyCounts={}, groupWinCounts={}, runnerUpCounts={}, thirdCounts={}; teams.forEach(t=>{winnerCounts[t.name]=0;qualifyCounts[t.name]=0;groupWinCounts[t.name]=0;runnerUpCounts[t.name]=0;thirdCounts[t.name]=0}); for(let i=0;i<runs;i++){ const tables=buildGroupTables(true); const qualified=getQualifiedTeams(tables); Object.keys(tables).forEach(g=>{groupWinCounts[tables[g][0].team]++; runnerUpCounts[tables[g][1].team]++}); qualified.forEach(t=>{qualifyCounts[t.team]++; if(t.qualification.startsWith("Third Group")) thirdCounts[t.team]++}); winnerCounts[simulateKnockout(qualified)]++; } return { winnerProbabilities:Object.entries(winnerCounts).map(([team,wins])=>({team,winProbability:Number(((wins/runs)*100).toFixed(2))})).sort((a,b)=>b.winProbability-a.winProbability), qualificationProbabilities:Object.entries(qualifyCounts).map(([team,count])=>({team,group:getTeam(team).group,qualifyProbability:Number(((count/runs)*100).toFixed(2)),groupWinProbability:Number(((groupWinCounts[team]/runs)*100).toFixed(2)),runnerUpProbability:Number(((runnerUpCounts[team]/runs)*100).toFixed(2)),thirdPlaceQualifyProbability:Number(((thirdCounts[team]/runs)*100).toFixed(2))})).sort((a,b)=>a.group.localeCompare(b.group)||b.qualifyProbability-a.qualifyProbability)}; }
function predictionAccuracy(){ const completed=predictions.filter(m=>m.actualResult); if(!completed.length) return {matchesPredicted:0,correctWinnerPercentage:0,correctScorePercentage:0,averageGoalError:0}; let cw=0, cs=0, err=0; completed.forEach(m=>{const p=m.predictedScore.split("-").map(Number), a=[Number(m.actualResult.homeGoals),Number(m.actualResult.awayGoals)]; const po=p[0]>p[1]?m.home:p[1]>p[0]?m.away:"Draw"; const ao=a[0]>a[1]?m.home:a[1]>a[0]?m.away:"Draw"; if(po===ao)cw++; if(p[0]===a[0]&&p[1]===a[1])cs++; err+=Math.abs(p[0]-a[0])+Math.abs(p[1]-a[1]);}); return {matchesPredicted:completed.length,correctWinnerPercentage:Number(((cw/completed.length)*100).toFixed(1)),correctScorePercentage:Number(((cs/completed.length)*100).toFixed(1)),averageGoalError:Number((err/completed.length).toFixed(2))}; }
const groupTables=buildGroupTables(false), qualifiedTeams=getQualifiedTeams(groupTables), mc=monteCarlo(10000);
fs.writeFileSync("data/tournament_simulation.json", JSON.stringify({generatedAt:new Date().toISOString(),groupTables,qualifiedTeams,winnerProbabilities:mc.winnerProbabilities,qualificationProbabilities:mc.qualificationProbabilities,predictionAccuracy:predictionAccuracy()}, null, 2));
console.log("Tournament simulation generated.");
console.log(`Qualified teams: ${qualifiedTeams.length}`);
console.log("Top winner:", mc.winnerProbabilities[0]);
console.log("Qualification probabilities generated.");
